Repository DiamondLightSource/PySIMRecon, pull requests merged in 2024-09, with the labels that each got.

#11 add '--shape' argument to OTF parser rather than hard-coded `(256, 256)`
  src/sim_recon/cli/otf.py
  src/sim_recon/cli/parsing.py
  src/sim_recon/files/images.py
  src/sim_recon/main.py
  src/sim_recon/otfs.py
Labels: enhancement

#22 Add matplotlib as dependency (for otf-view)
  pyproject.toml
Labels: bug

#28 Link pycudasirecon and cudasirecon in README
  README.md
  docs/template.md
Labels: documentation

#27 Use pre-commits
  .pre-commit-config.yaml
  pyproject.toml
Labels: enhancement

#24 `parse_recon_args`: allow `--output-directory` to be `None` by default
  src/sim_recon/cli/parsing/recon.py
Labels: bug

#36 `_prepare_files`: simplify by removing single channel condition
  src/sim_recon/recon.py
Labels: bug

#37 `dv_to_tiff`: correct pixel size argument in call to `write_tiff`
  src/sim_recon/images/__init__.py
Labels: bug

#34 `get_wavelengths_from_dv`: handle `dv.extFloats` that are `np.recarray`s
  src/sim_recon/images/dv.py
Labels: bug

#38 `image_resolution_from_mrc`: create and use it in `get_image_data` & `write_dv`
  src/sim_recon/images/dataclasses.py
  src/sim_recon/images/dv.py
Labels: bug

#44 Changed otf view display amplitude and phase and not real and imaginary
  src/sim_recon/otf_view.py
Labels: bug

#56 Specify use of conda-forge channel
  README.md
  docs/sections/installation.md
Labels: documentation

#57 Improve exception handling
  src/exceptions.py
  src/sim_recon/cli/dv_to_tiff.py
  src/sim_recon/files/config.py
  src/sim_recon/files/utils.py
  src/sim_recon/images/dv.py
  src/sim_recon/images/tiff.py
  src/sim_recon/otf_view.py
  src/sim_recon/recon.py
  src/sim_recon/settings/dataclasses.py
Labels: enhancement

#39 Enable `sim-recon` and `sim-otf` without a config
  README.md
  docs/help/sim_otf.txt
  docs/help/sim_recon.txt
  src/sim_recon/cli/otf.py
  src/sim_recon/cli/parsing/otf.py
  src/sim_recon/cli/parsing/recon.py
  src/sim_recon/cli/recon.py
  src/sim_recon/files/config.py
  src/sim_recon/main.py
  src/sim_recon/settings/dataclasses.py
Labels: enhancement

#67 Improve log files
  src/sim_recon/files/config.py
  src/sim_recon/files/utils.py
  src/sim_recon/images/dataclasses.py
  src/sim_recon/otfs.py
  src/sim_recon/recon.py
Labels: enhancement

#55 Require cudasirecon>=1.2.0
  README.md
  conda_requirements.txt
  docs/sections/installation.md
  pyproject.toml
Labels: bug, documentation

#54 Improve setting handling
  README.md
  docs/help/sim_otf.txt
  docs/help/sim_recon.txt
  src/sim_recon/cli/parsing/shared.py
  src/sim_recon/settings/formatting.py
Labels: bug

#47 Add `depends_on` option for override settings
  README.md
  docs/help/sim_recon.txt
  src/sim_recon/cli/parsing/otf.py
  src/sim_recon/cli/parsing/recon.py
  src/sim_recon/cli/parsing/shared.py
  src/sim_recon/recon.py
  src/sim_recon/settings/formatting.py
Labels: bug

#68 Do not create blank DV files
  src/sim_recon/images/dv.py
  src/sim_recon/images/tiff.py
  src/sim_recon/recon.py
Labels: enhancement

#62 handle DV OTFs
  src/sim_recon/images/tiff.py
  src/sim_recon/recon.py
Labels: enhancement

#69 Add `--allow-missing-channels` argument to `sim-recon`
  src/sim_recon/cli/parsing/recon.py
  src/sim_recon/cli/recon.py
  src/sim_recon/main.py
  src/sim_recon/recon.py
Labels: enhancement

#52 Generate docs only on changes to 'main' branch
  .github/workflows/generate_README.yaml
  .github/workflows/generate_help_docs.yaml
  .github/workflows/trigger_docs_generation.yaml
Labels: documentation

#59 Explain configs in more detail
  docs/sections/command_line.md
  docs/sections/configuration.md
  docs/sections/installation.md
Labels: documentation

#65 Allow missing headers in per channel configs
  src/sim_recon/files/config.py
  src/sim_recon/main.py
Labels: bug
